### ISSUE TITLE
After Upgrading to 24.25.0, Still receive Unable to write content to request stream; content would exceed Content-Length on Schema Export

### ISSUE THREAD

**Issue by greglong1** [Bertverbeek4PS/bc2adls#170]
I originally had a Oct 2023 version of bc2adls.  Unfortunately BC was upgraded to V24 and I experienced the following issue when exporting the schema:
"Unable to write content to request stream; content would exceed Content-Length"
From other issues logged, my understanding is that this would be resolved with the latest version of bc2adls.  Our BC developers have now upgraded to version 24.25.0 and after upgrading to this version in my test environment, I am still experiencing this error. 

![image](https://github.com/user-attachments/assets/64c2b334-1e68-4678-9b1c-a7bfc48fe41c)

![image](https://github.com/user-attachments/assets/2b73efef-1fc2-4085-920c-71649662d3d4)

![image](https://github.com/user-attachments/assets/857c0b4e-5e55-4195-b3ca-e5b93f99b52c)

**Comment by greglong1** [comment]
I also uninstalled and reinstalled the bc2adls, but this did not resolve the error message.

**Comment by greglong1** [comment]
I've also tried a fresh install on another sandbox and still get the same error message

**Comment by Bertverbeek4PS** [comment]
Hi @greglong1 very strange. It should be resolved with pull request https://github.com/Bertverbeek4PS/bc2adls/pull/108/files
I also cannot reproduce it.
But could you change your lakehouse and workspace to the guids? Because that is also a change that we have made later on. You cannot have spaces etc in the name.

Otherwise maybe arrange a call if the guids also not working. Then I can debug it.

**Comment by Bertverbeek4PS** [comment]
@greglong1 just did a try with exact the same setup as in your picture. But exporting the schema en the data is successfull. No errors.

**Comment by greglong1** [comment]
@Bertverbeek4PS - I tested entering the guids but still the same error and have check the Entra Application setup.  I will go back to our BC developers to ensure that the code from pull 108 has been included.  If still no joy we may need to arrange a call.  Thanks for your time.  Greg

**Comment by greglong1** [comment]
@Bertverbeek4PS - our BC developers have provided an updated version of 24.25.0 and in initial testing I no longer get the error message.  Will close this issue.  Bert - many thanks for your assistance.
